$(document).ready(function(){
    $(".menu").each(function(){
        $(this).click(function(){
            let id = $(this).attr("plink");
            $.ajax({
                url:"pages/"+id+".php",
                beforeSend:function()
                {
                    //$(this).addClass("disabled");
                },
                cache:false,
                success:function(response)
                { 
                    $(".right").html(response);
                }
            })
        })
    })
})