$(document).ready(function(){
    $("#settingbtn").click(function(){
        $.ajax({
            type:"POST",
            url:"setting.php",
            success:function(response)
            {
                $(".dataload").html(response);
            }
        })
    })
})